use_frameworks!

target 'FDKit_Example' do
  pod 'FDKit', :path => '../'

  #UI
#  pod 'Masonry'
#  pod 'SDWebImage'
#  pod 'SVPullToRefresh'
#  pod 'MBProgressHUD'
#  pod 'WMPageController'
#  #Model
#  pod 'YYModel'
#  pod 'WCDB'
#  pod 'YYCache'
#  #Network
#  pod 'AFNetworking'
#  #Debug
#  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
#  pod 'CocoaLumberjack'
#  
#  #性能检测
#  #内存泄漏
#  pod 'MLeaksFinder'
#  #循环引用
#  pod 'FBRetainCycleDetector'
#  
#  pod 'KMCGeigerCounter'
#  pod 'SystemServices', '~> 2.0.1'
#  #    pod 'PLCrashReporter'
#  pod 'KSCrash', '~> 1.15'

  pod 'Aspects'
#  
#  #组件化
#  pod 'CTMediator'
  
  target 'FDKit_Tests' do
    inherit! :search_paths

    
  end
end
